### ISSUE TITLE
Is this stable?

### ISSUE THREAD

**Issue by cerupcat** [simonnorberg/kortholt#1]
I'd love to try your implementation of this. Any recommendations on where to start? Have you considered adding input as well?

**Comment by simonnorberg** [comment]
Hi, thanks for trying this out.

I have updated the [readme](https://github.com/simonnorberg/kortholt/blob/master/README.md) with more instructions.

Input support is not planned right now.

**Comment by cerupcat** [comment]
Sorry for the delay. I'd love to use this, but unfortunately, it requires microphone input. I have my own implementation, but it doesn't run well on certain devices.

**Comment by rpattabi** [comment]
Hi @cerupcat, We have also built an experimental oboe glue for libpd with microphone input. On the few devices we have it appears to be working fine without problems.

You mentioned that your implementation doesn't run well on certain devices. Could you provide some details?

**Comment by cerupcat** [comment]
@rpattabi are you able to share your implementation?

The issues I see are a bit random. I've had to turn off using AAudio since some devices I couldn't get working with Bluetooth. Then, on some devices, there's issues with OpenSL with glitching audio due to buffer underruns. This might be based on my implementation though which uses oboe's example of FullDuplex.

I'd love to see your implementation and test it to see if yours is more stable.

**Comment by rpattabi** [comment]
Hi @cerupcat, We have forked `pd-for-android` and `libpd`, added oboe glue. As with your implementation, we also used oboe's example of FullDuplex (from `LiveEffect` sample). In our case, we extended it.

https://github.com/kuyil/pd-for-android/tree/oboe
https://github.com/kuyil/libpd/commits/oboe

Some key info:
 - Clone our pd-for-android fork and initialize submodules. Our libpd fork is a submodule and it incorporates our oboe glue (`oboe_stream`). libpd submodule in turn has oboe as submodule.
 - Be sure to add mavenLocal() to your project's build.gradle and use `implementation org.puredata.android:PdCore:1.1.2-LOCAL`.
 - CMake and ndk-build cannot work together in a same project. So to build oboe, instead of using cmake, we've updated libpd's Android.mk for use in ndk-build. So oboe is built through libpd. (We filed [this issue](https://github.com/google/oboe/issues/779) on oboe to support ndk-build.)
 - In order to build, all you need to do is to run `./gradlew publish`. This builds oboe, libpd, and PdCore and publish it to maven local.

Eager to know how this works on your devices.

P.S. There seems to be problem pausing and resuming AAudio stream. This might be the reason why you also experience problem with Bluetooth. A fresh start of the app while already connected to bluetooth works for us.

**Comment by cerupcat** [comment]
Thanks @rpattabi. I haven't had a chance to test, but I'll try it hopefully in the next few weeks.

Have you had any issues reported as of yet?

In terms of Bluetooth, restarting the app isn't really a proper enough solution as end users wouldn't know to do this.

**Comment by rpattabi** [comment]
You're right about Bluetooth. As you observed it is issue only with AAudio. Because of this, we decided to go with OpenSL (through oboe) for now.
